"""
Constants
"""

# Data file path and worksheet name
DATA_PATH = "./data/StateUniversity.xlsx"
INPUT_SHEET_NAME = "Data"
OUTPUT_SHEET_NAME = "Solution_Gurobi"

# cost per computer
INPUT_COMPUTER_COST_START_ROW = 4
INPUT_COMPUTER_COST_START_COL = 3

# cost of delivery
INPUT_DELIVERY_COST_START_ROW = 5
INPUT_DELIVERY_COST_START_COL = 3

# total demand of State University
INPUT_TOTAL_DEMAND_START_ROW = 9
INPUT_TOTAL_DEMAND_START_COL = 2

# maximum order quantity
INPUT_MAX_QUANTITY_START_ROW = 6
INPUT_MAX_QUANTITY_START_COL = 3

# minimun order quantity
INPUT_MIN_QUANTITY_START_ROW = 7
INPUT_MIN_QUANTITY_START_COL = 3

# Output result location
OUTPUT_WHETHER_TO_ORDER_START_ROW = 2
OUTPUT_WHETHER_TO_ORDER_START_COL = 2

OUTPUT_QUANTITY_TO_ORDER_START_ROW = 3
OUTPUT_QUANTITY_TO_ORDER_START_COL = 2

OUTPUT_MINIMUM_COST_START_ROW = 5
OUTPUT_MINIMUM_COST_START_COL = 2

OUTPUT_VENDOR_NAME_START_ROW = 1
OUTPUT_VENDOR_NAME_START_COL = 2

OUTPUT_WHETHER_TO_ORDER_NAME_ROW = 2
OUTPUT_WHETHER_TO_ORDER_NAME_COL = 1

OUTPUT_QUANTITY_TO_ORDER_NAME_ROW = 3
OUTPUT_QUANTITY_TO_ORDER_NAME_COL = 1

OUTPUT_TOTAL_COST_ROW = 5
OUTPUT_TOTAL_COST_COL = 1

TOTAL_COST_NAME = "Total Cost"

# Investment names list
VENDOR_NAMES = ["Vendor_1", "Vendor_2", "Vendor_3"]

# Decision Variable Names
WHETHER_TO_ORDER_NAME = "whether to order"
QUANTITY_TO_ORDER_NAME = "quantity to order"

# Constraint Names
TOTAL_DEMAND_NAME = "totalDemand"
MAX_QUANTITY_NAME = "max"
MIN_QUANTITY_NAME = "min"


# Model name
MODEL_NAME = "StateUniversity"
